In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.sparse import spdiags, kron, eye
from scipy.sparse.linalg import aslinearoperator

# AMATH 581 Homework 4
## Eric Leonard, ericcl@uw.edu

## Problem 1
The time evolution of the vorticity $\omega(x, y, t)$ and streamfunction $\psi(x, y, t)$ are given by the governing equations:

$$\omega_t + [\psi, \omega] = \nu\nabla^2 \omega$$

where $[\psi, \omega] = \psi_x\omega_y − \psi_y\omega_x$, $\nabla^2 = \partial^2_x + \partial^2_y$, 

and the streamfunction satisfies

$$\nabla^2\psi = \omega$$

Boundary Conditions: Assume periodic boundary conditions for both vorticity and streamfunction.

**(a)** Using the **spdiags** command, generate the three matrices $\textbf{A} = \partial^2_x + \partial^2_y$, $\textbf{B} = \partial_x$, and $\textbf{C} = \partial_y$ which take these derivatives in two dimensions.

**ANSWERS**: With $x, y \in [−10, 10]$, $n = 8$, write out the matrix solutions of your numerical evolution as ```A1```,
```A2``` and ```A3``` for $\textbf{A}$, $\textbf{B}$ and $\textbf{C}$ respectively.

**NOTE**: You can’t write out sparse matrices to ASCII files, so be sure to first make the matrices full.

In [2]:
# Define parameters
L = 20  # domain length (from -10 to 10, so length is 20)
n = 8   # number of points in each direction
h = L / n  # grid spacing

# Create finite difference matrices with periodic boundary conditions
# 1D second derivative matrix with periodic boundary
e = np.ones(n)
D2 = spdiags([e, -2 * e, e], [-1, 0, 1], n, n).toarray()
D2[0, -1] = 1  # periodic boundary condition
D2[-1, 0] = 1
D2 = D2 / h**2  # scale by h^2

# 1D first derivative matrix with periodic boundary for x-derivative
D1x = spdiags([-e, e], [-1, 1], n, n).toarray()
D1x[0, -1] = -1  # periodic boundary condition
D1x[-1, 0] = 1
D1x = D1x / (2 * h)  # scale by 2h

# 1D first derivative matrix with periodic boundary for y-derivative
D1y = D1x.copy()  # Same structure due to symmetry

# Construct 2D Laplacian matrix (A = ∂²_x + ∂²_y)
I = eye(n).toarray()  # identity matrix
A = kron(I, D2) + kron(D2, I)

# Construct 2D partial derivative matrices (B = ∂_x, C = ∂_y)
B = kron(D1x, I)  # partial derivative with respect to x
C = kron(I, D1y)  # partial derivative with respect to y

# Convert sparse matrices to full arrays for ASCII output
A1 = A.toarray()  # Laplacian matrix
A2 = B.toarray()  # x-derivative matrix
A3 = C.toarray()  # y-derivative matrix

A1, A2, A3

(array([[-0.64,  0.16,  0.  , ...,  0.  ,  0.  ,  0.  ],
        [ 0.16, -0.64,  0.16, ...,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.16, -0.64, ...,  0.  ,  0.  ,  0.  ],
        ...,
        [ 0.  ,  0.  ,  0.  , ..., -0.64,  0.16,  0.  ],
        [ 0.  ,  0.  ,  0.  , ...,  0.16, -0.64,  0.16],
        [ 0.  ,  0.  ,  0.  , ...,  0.  ,  0.16, -0.64]]),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 array([[ 0. ,  0.2,  0. , ...,  0. ,  0. ,  0. ],
        [-0.2,  0. ,  0.2, ...,  0. ,  0. ,  0. ],
        [ 0. , -0.2,  0. , ...,  0. ,  0. ,  0. ],
        ...,
        [ 0. ,  0. ,  0. , ...,  0. ,  0.2,  0. ],
        [ 0. ,  0. ,  0. , ..., -0.2,  0. ,  0.2],
        [ 0. ,  0. ,  0. , ...,  0. , -0.2,  0. ]]))