In [1]:
import numpy as np

# AMATH 581 Homework 1
## Eric Leonard, ericcl@uw.edu

## Problem 1
Consider the function

$$f(x) = x \sin(3x) − \exp(x)$$

and solve for the $x$-value near $x \approx −0.5$ that satisfies $f(x) = 0$. In the first part, use
the Newton-Raphson method with the initial guess $x(1) = −1.6$ to converge (in absolute
value) to the solution to $10^{−6}$. 

Keep track of the number of iterations until convergence
is achieved (NOTE: please check convergence with $f(x_n)$ not $f(x_{n+1}))$. In the second
part, use bisection with the initial end points $x = −0.7$ and $x = −0.4$. Keep track of the
mid point values and number of iterations until an accuracy of $10^{−6}$ is achieved.

ANSWERS: Should be written out as A1.npy, A2.npy, and A3.npy. Specifically, A1.npy
is the vector of $x$-values in the Newton method starting with the initial guess $x(1) = −1.6$, and A2.npy is the mid point ($x_{mid}$) values in the bisection method for successive iterations. A3.npy is a $1\times2$ vector with the number of iterations for the Newton and bisection respectively as the two components.

In [2]:
def Newton(f, fprime, x0, tol):
    """
    Perform Newton's method to find the root of a function f, starting from an initial guess x0.
    
    Parameters:
    f : function
        The function for which we want to find the root.
    fprime : function
        The derivative of the function f.
    x0 : float
        The initial guess for the root.
    tol: float
        The tolerance the solution needs to converge to before stopping.
    
    Returns:
    numpy.ndarray
        An array of the successive approximations (steps) for the root, where each entry is a refined guess.
    """
    steps = [x0]
    while True:
        x0 -= f(x0) / fprime(x0)
        steps.append(x0)
        if abs(f(steps[-2])) < tol:
            break
        
    return np.array(steps)



def bisection(f, a, b, tol):
    """
    Find a root of the function f within the interval [a, b] using the bisection method.
    
    Parameters:
    f : function
        The function whose root is to be found.
    a : float
        The left-most endpoint of the starting interval.
    b : float
        The right-most endpoint of the starting interval.
    tol : float
        An array The tolerance; the algorithm stops when the interval is smaller than tol.
    
    Returns:
    numpy.ndarray
        An array of the successive approximations (steps) for the root, where each entry is a refined guess.
    """
    if f(a) * f(b) > 0:
        raise ValueError("The function must have opposite signs at a and b. Try a new interval.")

    midpoints = []
    while True:
        midpoint = (a + b) / 2.0
        midpoints.append(midpoint)
        f_mid = f(midpoint)
        if abs(f((b + a) / 2.0)) < tol:
            break
        if f(a) * f_mid < 0:
            b = midpoint
        else:
            a = midpoint
            
    return np.array(midpoints)

In [3]:
f = lambda x: x * np.sin(3*x) - np.exp(x)
fprime = lambda x: np.sin(3*x) + 3 * x * np.cos(3*x) - np.exp(x)

In [4]:
A1 = Newton(f, fprime, -1.6, 1e-6)
print(A1)

[-1.6         3.19799514  2.46440244  1.2035359   0.65020146 -0.11692334
 -0.66052349 -0.52192654 -0.56655274 -0.57074658 -0.57078962 -0.57078962]


In [5]:
A2 = bisection(f, -0.7, -0.4, 1e-6)
print(A2)

[-0.55       -0.625      -0.5875     -0.56875    -0.578125   -0.5734375
 -0.57109375 -0.56992188 -0.57050781 -0.57080078 -0.5706543  -0.57072754
 -0.57076416 -0.57078247 -0.57079163 -0.57078705 -0.57078934]


In [6]:
A3 = np.array([len(A1)-1, len(A2)]) #subtract 1 from newton's to not count the initial x0 as an iteration
print(A3)

[11 17]


## Problem 2
Let the following be defined:

$$\textbf{A} = \begin{bmatrix}
1 & 2\\
-1 & 1
\end{bmatrix},\ 
\textbf{B} = \begin{bmatrix}
2 & 0\\
0 & 2
\end{bmatrix},\ 
\textbf{C} = \begin{bmatrix}
2 & 0 & -3\\
0 & 0 & -1
\end{bmatrix},\ 
\textbf{D} = \begin{bmatrix}
1 & 2\\
2 & 3\\
-1 & 0
\end{bmatrix},\ 
\textbf{x} = \begin{bmatrix}
1\\
0
\end{bmatrix},\ 
\textbf{y} = \begin{bmatrix}
0\\
1
\end{bmatrix},\ 
\textbf{z} = \begin{bmatrix}
1\\
2\\
-1
\end{bmatrix},\ 
$$

Calculate the following:

**(a)** $\textbf{A} + \textbf{B}$, 

**(b)** $3\textbf{x} - 4\textbf{y}$, 

**(c)** $\textbf{A}\textbf{x}$, 

**(d)** $\textbf{B}(\textbf{x}-\textbf{y})$, 

**(e)** $\textbf{D} \textbf{x}$, 

**(f)** $\textbf{D} \textbf{y} + \textbf{z}$, 

**(g)** $\textbf{AB}$, 

**(h)** $\textbf{BC}$, 

**(i)** $\textbf{CD}$

In [7]:
A = np.array([[1, 2],
             [-1, 1]])
B = np.array([[2, 0],
                [0, 2]])
C = np.array([[2, 0, -3],
              [0, 0, -1]])
D = np.array([[1, 2],
              [2, 3],
              [-1, 0]])
x = np.array([[1], 
              [0]])
y = np.array([[0],
              [1]])
z = np.array([[1],
              [2],
              [-1]])

In [8]:
A4 = A + B
A5 = (3*x - 4*y).T[0]
A6 = (A @ x).T[0]
A7 = (B @ (x - y)).T[0]
A8 = (D @ x).T[0]
A9 = (D @ y + z).T[0]
A10 = A @ B
A11 = B @ C
A12 = C @ D

Q2 = [globals()[f"A{i}"] for i in range(4,13)]
for i, ans, in enumerate(Q2):
    print(f"A{i+4}:")
    print(ans)
    print()

A4:
[[ 3  2]
 [-1  3]]

A5:
[ 3 -4]

A6:
[ 1 -1]

A7:
[ 2 -2]

A8:
[ 1  2 -1]

A9:
[ 3  5 -1]

A10:
[[ 2  4]
 [-2  2]]

A11:
[[ 4  0 -6]
 [ 0  0 -2]]

A12:
[[5 4]
 [1 0]]

